version: "3"
services:
  wolweb:
    build: .
    container_name: wolweb
    image: "wolweb"
    
    # Have to use host mode as bridge network has issues with UDP broadcast
    # https://github.com/docker/for-linux/issues/637
    # ports:
    #   - 12345:8089
    network_mode: host

    #environment:
      #WOLWEBPORT: "8089"
